use_frameworks!

platform :ios, '8.0'

target 'HXZKLib_Example' do
  pod 'HXZKLib', :path => '../'

  target 'HXZKLib_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
